Repository 2024-Winter-BootCamp-TeamD/review-Backend, pull requests merged in 2025-01, with the labels that each got.

#4 사용자 정보 조회
  apiserver/settings.py
  apiserver/urls.py
  user/admin.py
  user/migrations/0001_initial.py
  user/migrations/0002_userprofile_created_at_userprofile_email_and_more.py
  user/migrations/0003_userprofile_github_id.py
  user/migrations/0004_userprofile_profile_image.py
  user/migrations/0005_remove_userprofile_avatar_url.py
  user/models.py
  user/serializers.py
  user/urls.py
  user/views.py
Labels: 기능 구현

#8 [feat] 사용자 정보 표시 수정 및 모드 설정 기능 구현
  apiserver/settings.py
  user/migrations/0006_userprofile_review_mode.py
  user/migrations/0007_alter_userprofile_review_mode.py
  user/models.py
  user/serializers.py
  user/urls.py
  user/views.py
Labels: 기능 구현, 리팩토링

#12 [feat/#11]부분 코드 받아오기 및 서버 요청
  apiserver/settings.py
  apiserver/urls.py
  partreview/__init__.py
  partreview/admin.py
  partreview/apps.py
  partreview/migrations/0001_initial.py
  partreview/migrations/0002_remove_codereview_mode_remove_codereview_review_and_more.py
  partreview/migrations/__init__.py
  partreview/models.py
  partreview/serializers.py
  partreview/tests.py
  partreview/urls.py
  partreview/views.py
Labels: 기능 구현

#17 [feat] 풀리퀘스트 리뷰 전체조회 기능 구현
  .gitignore
  Dockerfile
  apiserver/asgi.py
  apiserver/settings.py
  apiserver/wsgi.py
  docker-compose.yml
  manage.py
  poetry.lock
  pullrequest/admin.py
  pullrequest/apps.py
  pullrequest/gpttest.py
  pullrequest/migrations/0001_initial.py
  pullrequest/models.py
  pullrequest/serializers.py
  pullrequest/tests.py
  pullrequest/urls.py
  pullrequest/views.py
  report/admin.py
  report/apps.py
  report/models.py
  report/tests.py
  report/views.py
  repository/admin.py
  repository/apps.py
  repository/tests.py
  repository/views.py
  user/apps.py
  user/migrations/0001_initial.py
  user/tests.py
Labels: 기능 구현

#20 [feat] 실시간 부분 코드 리뷰(DEEPSEEK) 기능 구현
  apiserver/settings.py
  partreview/migrations/0003_alter_codereview_user.py
  partreview/models.py
  partreview/urls.py
  partreview/views.py
  poetry.lock
  user/admin.py
  user/migrations/0001_initial.py
  user/migrations/0002_alter_user_review_mode.py
  user/migrations/__init__.py
  user/models.py
  user/serializers.py
Labels: 기능 구현

#21 Feat/#10 메인 기능 구현
  apiserver/settings.py
  apiserver/urls.py
  oauth/urls.py
  oauth/views.py
  partreview/migrations/0001_initial.py
  partreview/migrations/0002_remove_codereview_mode_remove_codereview_review_and_more.py
  poetry.lock
  pullrequest/migrations/0001_initial.py
  pullrequest/migrations/0002_remove_prreview_title.py
  pullrequest/migrations/0003_prreview_title.py
  pullrequest/models.py
  pyproject.toml
  repository/migrations/0001_initial.py
  repository/models.py
  review/urls.py
  review/utils/fileReview.py
  review/utils/prReview.py
  review/utils/prompts/newbiePrompt.py
  review/views.py
Labels: 기능 구현

#27 [feat] PR 전체조회, 검색기능에 페이지네이션 추가
  apiserver/settings.py
  partreview/migrations/0001_initial.py
  pullrequest/migrations/0001_initial.py
  pullrequest/views.py
  repository/migrations/0001_initial.py
  repository/models.py
  user/migrations/0001_initial.py
Labels: 기능 구현

#31 [feat] 최신 7개 PR의 평균 등급 조회 기능 구현
  apiserver/settings.py
  pullrequest/urls.py
  pullrequest/views.py
Labels: 기능 구현

#33 [feat] 전체 report, 추가, 선택된 report 조회 기능 추가
  apiserver/settings.py
  apiserver/urls.py
  pullrequest/migrations/0001_initial.py
  pullrequest/migrations/0002_alter_prreview_id.py
  pullrequest/models.py
  report/apps.py
  report/migrations/0001_initial.py
  report/migrations/0002_alter_report_table_alter_reportprreview_table.py
  report/models.py
  report/urls.py
  report/views.py
  repository/migrations/0001_initial.py
  user/views.py
Labels: 기능 구현

#37 [feat] Report 다운로드 링크 제공 기능 추가
  report/urls.py
  report/views.py
Labels: 기능 구현

#39 [feat] 전체 PR 모드 카테고리 통계 조회, 리팩토링
  apiserver/settings.py
  apiserver/urls.py
  pullrequest/urls.py
  pullrequest/views.py
Labels: 기능 구현, 리팩토링

#40 [feat/#38] Report에 사용된 PR 모드 확인 기능 추가 및 이전 코드 보완
  report/urls.py
  report/views.py
Labels: 기능 구현

#42 [refactor/#41] API명세서에 맞춘 코드 수정
  report/views.py
Labels: 리팩토링

#45 [refactor/#44] pr-review 코드를 API 명세서와 맞춤
  pullrequest/views.py
Labels: 리팩토링

#48 [Refactor/#46] pr_review views.py 리팩토링
  pullrequest/views.py
Labels: 리팩토링

#50 [fix/#49] QuerySet을 딕셔너리 접근이 가능하도록 변환
  pullrequest/views.py
Labels: 이슈해결

#53 [refactor/#52] 보고서 삭제 확인 기능 수정
  apiserver/settings.py
  apiserver/urls.py
  report/views.py
Labels: 리팩토링

#70 [feat/#58] PR리뷰 총평까지 달리도록 수정(모드 고정)
  apiserver/settings.py
  review/utils/prReview.py
Labels: 기능 구현

#74 [Issue/#72] CORS 설정 추가
  apiserver/settings.py
  poetry.lock
  pyproject.toml
Labels: 이슈해결

#77 [feat/#76] repository 필드 추가
  apiserver/settings.py
  oauth/views.py
  repository/migrations/0001_initial.py
  repository/models.py
  repository/serializers.py
  repository/views.py
Labels: 기능 구현

#78 feat: 전체 기간 일별 PR 평균 등급 조회 기능 구현
  apiserver/settings.py
  partreview/migrations/0001_initial.py
  pullrequest/migrations/0001_initial.py
  pullrequest/urls.py
  pullrequest/views.py
  report/migrations/0001_initial.py
  repository/migrations/0001_initial.py
  user/migrations/0001_initial.py
Labels: 기능 구현

#81 [issue/#80] 누락코드 추가
  repository/views.py
Labels: 이슈해결

#82 [feat/#79] 문제 유형 조회 시 대분류 함께 반환
  partreview/migrations/0001_initial.py
  pullrequest/migrations/0001_initial.py
  pullrequest/views.py
  report/migrations/0001_initial.py
  repository/migrations/0001_initial.py
  user/migrations/0001_initial.py
Labels: 기능 구현

#87 [issue/#86] 연동 위한 수정 적용
  apiserver/settings.py
  oauth/views.py
  pyproject.toml
  report/views.py
Labels: 이슈해결

#90 [feat/#89] 모드에 맞는 problem_type 반환 기능 추가
  apiserver/settings.py
  poetry.lock
  review/tasks.py
  review/utils/fileReview.py
  review/utils/prReview.py
  review/views.py
  user/migrations/0002_alter_user_review_mode.py
  user/migrations/0003_alter_user_review_mode.py
  user/models.py
Labels: 기능 구현

#97 [refactor/#91] review 1차 리팩토링
  apiserver/settings.py
  pullrequest/views.py
  review/common.py
  review/tasks.py
  review/views.py
Labels: 리팩토링

#105 [FEAT] GCP이용 서버 배포
  apiserver/settings.py
Labels: 기능 구현

#108 [refactor/#107] 부분 코드리뷰 수정
  apiserver/settings.py
  partreview/views.py
Labels: 리팩토링

#109 [Refactor/#98] review 비동기 최적화
  review/common.py
  review/tasks.py
  review/views.py
Labels: 리팩토링

#111 [ISSUE] 부분 코드 리뷰 스트리밍 늦게 시작하는 문제 해결
  apiserver/settings.py
  partreview/views.py
Labels: 이슈해결

#116 [feat/#115] 파일리뷰 댓글에 점수, 등급 포함
  apiserver/settings.py
  report/reports/20250123064111_report.pdf
  review/tasks.py
Labels: 기능 구현

#122 [refactor/#118] 모드 추가 및 프롬프팅 개선
  apiserver/settings.py
  review/tasks.py
  review/utils/fileReview.py
  review/utils/prompts/filePrompts.py
  review/utils/prompts/prPrompts.py
  review/utils/prprompts/__init__.py
  review/utils/prprompts/prcleanPrompt.py
  review/utils/prprompts/proptimizePrompt.py
Labels: 리팩토링

#131 [ISSUE/#130] 리팩토링 실수 고침
  review/tasks.py
Labels: 이슈해결

#135 [FEAT/#134] 선택된 PRReview 정보 반환 기능 구현
  apiserver/settings.py
  pullrequest/urls.py
  pullrequest/views.py
  report/reports/20250125090410_report.pdf
  report/reports/20250125170402_report.pdf
  review/tasks 복사본.py
  review/tasks.py
Labels: 기능 구현

#137 [FEAT/#129] review 리팩토링 및 프롬프트 수정
  apiserver/settings.py
  review/common.py
  review/tasks.py
  review/utils/prompts/filePrompts.py
  review/utils/prompts/y_filePrompts.py
  review/utils/prprompts/__init__.py
  review/utils/prprompts/prcleanPrompt.py
  review/utils/prprompts/proptimizePrompt.py
Labels: 리팩토링

#139 [FEAT/#138] Merge blocking 확대 적용, github_webhook 수정, prreviewselectview 반환값 추가
  apiserver/settings.py
  pullrequest/views.py
  review/tasks.py
  review/utils/prompts/filePrompts.py
  review/views.py
Labels: 기능 구현

#142 [refactor/#141] 프롬프트 개선 (코드 스니펫)
  apiserver/settings.py
  review/utils/prompts/filePrompts.py
Labels: 리팩토링

#144 [Refactor/#140] 리팩토링, 프롬프팅
  review/common.py
  review/tasks.py
  review/utils/fileReview.py
  review/utils/prompts/filePrompts.py
  review/utils/prompts/prPrompts.py
  review/views.py
Labels: 리팩토링

#149 [Feat/#146] 타임아웃 기능 구현
  apiserver/settings.py
  review/tasks.py
  review/utils/prompts/filePrompts.py
Labels: 기능 구현
